services:
  sip-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: sip-ai-agent
    restart: unless-stopped
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "5060:5060/udp"
      - "16000-16100:16000-16100/udp"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    container_name: sip-ai-dashboard
    depends_on:
      - sip-agent
    restart: unless-stopped
    ports:
      - "8080:80"
