name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIP_DOMAIN: example.com
      SIP_USER: "1001"
      SIP_PASS: secret
      OPENAI_API_KEY: test-key
      AGENT_ID: test-agent
      ENABLE_SIP: "true"
      ENABLE_AUDIO: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libpcap-dev \
            portaudio19-dev \
            python3-dev \
            swig
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Lint
        run: make lint
      - name: Type check
        run: make type
      - name: Tests
        run: make test
