name: CI

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SIP_DOMAIN: example.com
      SIP_USER: "1001"
      SIP_PASS: secret
      OPENAI_API_KEY: test-key
      AGENT_ID: test-agent
      ENABLE_SIP: "true"
      ENABLE_AUDIO: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libpcap-dev \
            portaudio19-dev \
            python3-dev \
            swig
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
      - name: Lint
        run: make lint
      - name: Type check
        run: make type
      - name: Tests
        run: make test
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Install frontend dependencies
        working-directory: web
        run: npm ci
      - name: Lint frontend
        working-directory: web
        run: npm run lint
      - name: Test frontend
        working-directory: web
        run: npm run test
      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Set latest tag
        if: github.ref == 'refs/heads/main'
        run: |
          echo "BACKEND_LATEST_TAG=ghcr.io/${{ github.repository_owner }}/sip-ai-agent-backend:latest" >> $GITHUB_ENV
          echo "DASHBOARD_LATEST_TAG=ghcr.io/${{ github.repository_owner }}/sip-ai-agent-dashboard:latest" >> $GITHUB_ENV
      - name: Build and push backend image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: backend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sip-ai-agent-backend:${{ github.sha }}
            ${{ env.BACKEND_LATEST_TAG }}
      - name: Build and push dashboard image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          target: dashboard
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sip-ai-agent-dashboard:${{ github.sha }}
            ${{ env.DASHBOARD_LATEST_TAG }}
